### ISSUE TITLE
Selective Fields 

### ISSUE THREAD

**Issue by dthowell** [mshanemc/AnythingPath#4]
Hi Shane!
This is so awesome! I was thinking someone smart would have already done this. Do you have it on the roadmap to add fields alongside the guidance for success? This is the part that we really are looking for. Being able to selectively show fields at each stage and make them required.

**Comment by mshanemc** [comment]
I've been tempted to do it a few times, but Salesforce overall roadmap has full Path/Guidance coming to all objects (#safeharbor) in the spring release.  So I'd rather just wait for the real deal.
