### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Mahwish7** [mshanemc/AnythingPath#6]
Hi

I am trying to deploy this tool but its giving following errors,

objects/GuidanceBox__c.object(3,2):Error parsing file: The content of elements must consist of well-formed character data or markup.
tabs/GuidanceBox__c.tab(GuidanceBox__c):In field: fullName - no CustomObject named GuidanceBox__c found
aura/GuidanceBox/GuidanceBox.cmp(GuidanceBox):Cannot find apex controller: GuidanceBox (namespace: null name: GuidanceBox)
classes/GuidanceBoxTest.cls(12,33):Invalid type: GuidanceBox__c

**Comment by Shubor** [comment]
Try my version, I fixed some merge errors on the guidance box object which made the guidance box object creation fail.

**Comment by mshanemc** [comment]
sorry for being sloppy there.  I merged @Shubor 's PR and would like to know if that fixed it

**Comment by Mahwish7** [comment]
Thanks Shubor for the reply . Well I fixed them all that day and it worked for me.
