### ISSUE TITLE
Unable to Deploy

### ISSUE THREAD

**Issue by maryfajimi** [mshanemc/AnythingPath#8]
Deployment Complete
Failures:
aura/AnythingBoard/AnythingBoard.cmp(AnythingBoard):No COMPONENT named markup://c:singleFieldDisplayerReadOnly found : [markup://c:AnythingBoard]
aura/AnythingBoard/AnythingBoard.design(AnythingBoard):No COMPONENT named markup://c:singleFieldDisplayerReadOnly found : [markup://c:AnythingBoard, markup://c:AnythingBoard]

**Comment by vmurugan19** [comment]
I have resolved the markup://c:singleFieldDisplayerReadOnly found failures.

**Comment by mshanemc** [comment]
I merged the PR in just now...is it working ok?

**Comment by vmurugan19** [comment]
Hi mshanemc,

How to set up Guidance box in Order. There is any sample vedio?

**Comment by orecus** [comment]
Doesn't seem to work, get the following errors when deploying;

`No COMPONENT named markup://c:singleFieldDisplayerReadOnly found : [markup://c:AnythingBoard, markup://c:AnythingBoard]`

`No COMPONENT named markup://c:singleFieldDisplayerReadOnly found : [markup://c:AnythingBoard]`

**Comment by mshanemc** [comment]
I added c:singleFieldDisplayerReadOnly to the package.xml...it was missing.  Thanks!
